### PR TITLE
Remove log warning for empty AWS values which spams the log file

### PR DESCRIPTION
**Pull request by TheConnMan**

### CODE REVIEW

**Comment by bdunavant** [comment]
I was the one who said to do this, but in thinking about it more, we may instead want to leave it, but add an ENV variable that lets us shut it off.  I don't understand the behavior well enough to just say "this is not an error" unless Matt agrees this is just normal behavior for AWS, and it's expected.   In that case, i'd comment the code out, rather than delete, with a note to future-us that it's commented out because it's an error, and annoying since it produces gaps in graphs (because someone will complain about the gaps, and the next programmer will put the log back), but that it's simply how AWS is right now, so the code is commented until AWS gets their stuff together.

**Comment by TheConnMan** [comment]
> I don't understand the behavior well enough to just say "this is not an error" unless Matt agrees this is just normal behavior for AWS, and it's expected.

Nulls are normal, but empty results can be an error. I agree that it's annoying, but it is an error sometimes. This is how CloudWatch has always functioned, so we need to work around it.

An env var sounds like a good idea. Log the warn while you're setting up the agent, but turn it off once you know it's working properly. What do you think?

**Comment by bdunavant** [comment]
Matt's opinion is the important one here, but I think the ENV is a good middle-ground.  It lets us selectively hide the logs that are spamming, while leaving them visible to new installs.  Are there others we expect to do this with?   Something generic like "QUIET_COMMON_WARNINGS" may be better in that case so we don't have a lot of new options.   If this is the only one, then a specific name is probably best.

**Comment by maier** [comment]
what level are the messages? if they are not `error` level, we could turn quiet on.

```
## Log only error level messages.
# quiet = false
```

**Comment by TheConnMan** [comment]
> what level are the messages? if they are not `error` level, we could turn quiet on.

These messages are `warn`, so quiet would work.

**Review by maier — APPROVED** [review]

**Pull request merged**
